export { default as Avatar } from "./Avatar.svg";
// export { default as Logo } from "./logo.png";
export { default as Chart } from "./Chart.svg";
export { default as ArrowDown } from "./arrow-down.svg";
export { default as ArrowLeft } from "./arrow-left.svg";
export { default as ArrowUp } from "./arrow-up.svg";
export { default as FinancialWorks } from "./financial-works.svg";
export { default as FinancialWorksActive } from "./financialWorksActive.svg";
export { default as ArrowRight } from "./arrow-right.svg";
export { default as GreenArrowUpRight } from "./green-arow-up-right.svg";
export { default as Home } from "./home.svg";
export { default as HomeActive } from "./home-active.svg";
export { default as Info } from "./info.svg";
export { default as Projects } from "./projects.svg";
export { default as ProjectsActive } from "./projects-active.svg";
export { default as UploadFiles } from "./upload-files.svg";
export { default as UploadFilesActive } from "./upload-files-active.svg";
export { default as SearchIcon } from "./searchIcon.svg";
export { default as TripleDots } from "./tripleDots.svg";
export { default as Trash } from "./trash.svg";
export { default as TrashFile } from "./trash-file.svg";
export { default as XIcon } from "./X.svg";
export { default as PenBold } from "./pen-bold.svg";
export { default as UploadFile } from "./uploadFile.svg";
export { default as Eye } from "./eye.svg";
export { default as EyeSlash } from "./eye-slash.svg";

export { default as P2PReport } from "./p2pReport.svg";
export { default as P2pReportActive } from "./p2pReportActive.svg";
// export { default as ProjectsReport } from "./projectsReport.svg";
export { default as ProjectsReportActive } from "./projectsReportActive.svg";
export { default as UploadFileIcon } from "./UploadFileIcon.svg";
export { default as DotSquare } from "./dotSquare.svg";
// export { default as TrelloLogoBrand } from "./TrelloLogoBrand.svg";
export { default as AtlassianIcon } from "./AtlassianIcon.svg";
export { default as SettingIcon } from "./settingIcon.svg";
export { default as StaredTabImg } from "./staredTabImg.svg";
export { default as Photos } from "./photos.svg";

